# ffc-pr-calculator.gitleaks.toml
title = "ffc-pr-calculator"

[extend]
path = ".gitleaks-shared/.gitleaks.toml"

# Service-specific additions only below this line, use [[ ]] for multiple allowlist instances
[allowlist]
description = "Service-specific exclusions"
paths = [
  '''test/mock-objects/.*''',
  '''test/mock-modules/.*''',
  '''test/unit/.*'''
]

#enter regex here wrapped in triple ''' to exclude specific keys
regexes = [
  '''defra.helpline@defra.gov.uk''',
  '''DefraGroupDataProtectionOfficer@defra.gov.uk''',
  '''contentteam@defra.gov.uk''',
  '''enquiries@environment-agency.gov.uk''',
]