services:
  ffc-pr-calculator:
    build:
      context: .
      target: production
    image: ffc-pr-calculator
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pr-calculator-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
