apiVersion: v2
description: Progressive reductions calculator
name: ffc-pr-calculator
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
  - name: ffc-helm-library
    version: 4.7.2
    repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
