environment: production
name: ffc-pr-calculator
namespace: ffc-pr
workstream: ffc-pr
image: ffc-pr-calculator

labels:
  component: web

appInsights:
  key:

containerConfigMap:
  name: ffc-pr-calculator-config-map

containerSecret:
  name: ffc-pr-calculator-container-secret
  type: Opaque

deployment:
  priorityClassName: high
  replicas: 2
  minReadySeconds: 0
  minReplicas: 2
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80

container:
  requestMemory: 100Mi
  requestCpu: 40m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  googleTagManagerKey: GTM-5XJKV8F

ingress:
  class: nginx
  endpoint: ffc-pr-calculator
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 5
