environment: development
name: ffc-pr-calculator
namespace: ffc-pr
workstream: ffc-pr
image: ffc-pr-calculator

labels:
  component: web

appInsights:
  key:

containerConfigMap:
  name: ffc-pr-calculator-config-map

containerSecret:
  name: ffc-pr-calculator-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: high
  replicas: 5
  minReadySeconds: 0
  runAsNonRoot: true
  runAsUser: 1000
  minReplicas: 5
  maxReplicas: 10
  cpuThreshold: 60
  memoryThreshold: 60

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3000
  googleTagManagerKey: GTM-5XJKV8F

ingress:
  class: nginx
  endpoint: ffc-pr-calculator
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 5
