environment: development
name: ffc-pr-calculator
namespace: ffc-pr
workstream: ffc-pr
image: ffc-pr-calculator

labels:
  component: web

appInsights:
  key:

containerConfigMap:
  name: ffc-pr-calculator-config-map

containerSecret:
  name: ffc-pr-calculator-container-secret
  type: Opaque

service:
  port: 80
  type: ClusterIP

deployment:
  restartPolicy: Always
  priorityClassName: high
  replicas: 1
  minReadySeconds: 0
  redeployOnChange: update this field to force a change
  runAsNonRoot: true
  runAsUser: 1000
  minReplicas: 1
  maxReplicas: 3
  cpuThreshold: 80
  memoryThreshold: 80
  updateMode: Off

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 60Mi
  limitCpu: 60m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  port: 3000
  googleTagManagerKey: tbc

ingress:
  class: nginx
  endpoint: ffc-pr-calculator
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
