---
environment: production
environmentCode: prd
container:
  endpointEnabled: true
ingress:
  server: azure.defra.cloud
  endpoint: ffc-pr-calculator-prd
secretProviderClass:
  azure:
    keyvaultName: PRDFFCINFKV1001
    objects:
      - objectName: prd-ffcahwr-appinsights-connectionString
        objectType: secret

  secretObjects:
    - secretName: ffc-pr-calculator
      type: Opaque
      data:
        - objectName: prd-ffcahwr-appinsights-connectionString
          key: APPINSIGHTS_CONNECTIONSTRING